version: 2.1

orbs:
  windows: circleci/windows@2.2.0

executors:
  winvm: windows/default

jobs:
  build:
    description: Build application with Release configuration
    executor: winvm
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "MatchingGame/MatchingGameCS.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "MatchingGame/MatchingGameCS.csproj" }}
      - run:
          name: "Create Windows Desktop Executable"
          command: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true
      - store_artifacts:
          path: C:\Users\circleci\project\MatchingGame\bin\Release\netcoreapp3.0\win-x64\publish\
          destination: executable
      - run:
          name: Set up a self-signed certificate to be able to Codesign
          command: powershell.exe scripts\SetupCertsLocal.ps1
      - run:
          name: Reset the system password to then create a priviledged session
          command: powershell.exe  scripts\PasswordResetCredsCert.ps1
      - run:
          name: Mount app to codesign and  sign artefact
          command: powershell.exe scripts\RunDockerMakeCert.ps1
      - run:
          name: Confirm if docker if docker if docker is installed 
          command: winpty docker run -v "C:\Users\circleci\project\MatchingGame\:C:\testapp"   mcr.microsoft.com/windows/servercore:ltsc2019 powershell.exe -executionpolicy bypass C:\testapp\scripts\makecert.ps1

workflows:
  build-and-sign:
    jobs:
      - build
